# Action to build lxd images
---
name: build lxd images

on:
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build-lxd-images:
    runs-on: ubuntu-22.04
    container:
      image: alpine:3.18.3
      #env:
      #  NODE_ENV: development
      #ports:
      #  - 80
      #volumes:
      #  - ${{ github.workspace }}:/data
      options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      #- name: Setup Distrobuilder
      #  uses: supertemaki/setup-distrobuilder@main
      #  with:
      #    channel: latest/stable

      #- name: Build lxd image container
      #  uses: supertemaki/distrobuilder-build@main

      #- name: Prepare for build
      #  run: |
      #    ./.github/workflows/scripts/prepare-for-build.sh

      #- name: Build lxd images
      #  run: |
      #    ./.github/workflows/scripts/build-lxd-images.sh

      - name: build
        uses: supertemaki/distrobuilder-build@main

      - name: Upload image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lxd-images
          path: distrobuilder.output
