name: build

on:
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  setup-distrobuilder:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Distrobuilder
      uses: supertemaki/setup-distrobuilder@main

    - name: Run ls
      run: |-
        ls -la
        ls -la build-out
        
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: build-out
